### ISSUE TITLE
pierre !

### ISSUE THREAD

**Issue by parisni** [a-tsioh/suatbun#1]
salut pierre c'est nicolas du limsi j'ai constaté ton départ
alors je te propose de rester en contact: niparisco at gmails point com
j'ai pas trouvé mieux que ton repos le plus obscurs et une issue pour ça
@+ autour d'une bierre ?

**Comment by a-tsioh** [comment]
haha elle est bien bonne celle là !
C'est vrai qu'il est obscur ce repos, j'avais presque oublié qu'un jour j'ai fait du django... (par contre le shuowen, je vais me replonger dedans... c'est p'tet un signe ;) )

La suite par mail (so issue closed tu vois un problème dans ce vieux code ?)
